### ISSUE TITLE
3_Main_script.R - Error in first function

### ISSUE THREAD

**Issue by naurasd** [DvBMolEc/rgbifanimals#9]
Hi

running your excellent workflow. However, in 3_main_script.R, I am getting an error right away in line 13 when running the sapply command:

``` r
sapply(df$Specieslist, function(species){
  print(species)
  tryCatch(find_closest_registered_place(species, Coordinates, tr, "Output/ShortestPath.csv"), error = function(e)return())
})
#> Error in df$Specieslist: object of type 'closure' is not subsettable
```

I tried this with my own data as well with your data, same issue.

Any idea what is happening here?

Cheers
Nauras

**Comment by TimBosman** [comment]
Hey, this seems like a problem with the column names of the input file. What is the output of `summary(df$Specieslist)`?

**Comment by naurasd** [comment]
hi Tim, thanks for the reply.

the output is...

```
Length     Class      Mode 
      661 character character 
```

**Comment by TimBosman** [comment]
Hey, that seems correct. While on the data that we are using the length is 427, but that should not really matter. So maybe there is a problem with the contents of the array. Can you check if the following gives the same output:
```
> str(df$Specieslist)
chr [1:427] "Acartia bifilosa" "Acartia clausi" "Acartia hudsonica"
````

**Comment by naurasd** [comment]
Ok, I don't know what's happening here, but the error does not occur any more. Maybe some other package was masking something before? not sure. 

So, no more error. Output of what you suggested is the same:

```
> str(df$Specieslist)
 chr [1:661] "Acartia (Acanthacartia) bifilosa" "Acartia (Acanthacartia) tonsa" ...
```

But when running the function, I get tons of warnings saying `Output/ShortestPath.csv` was not found:

```
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In file(con, "rb") :
  cannot open file 'Output/ShortestPath.csv': No such file or directory
2: In file(con, "rb") :
  cannot open file 'Output/ShortestPath.csv': No such file or directory
.
.
.
```
It is difficult for me to understand where the .csv file is supposed to come from, because it does neither seem to be created during 1_Preparation.R, nor 2_Functions.R or 3_Main_script.R. Where is this file supposed to come from?

**Comment by TimBosman** [comment]
This file is created by the 3_Main_script.R file. The problem here is that we check in the file if your Species and location combination is in your file. But since the file does not exist yet, it throws a warning. Later in that function we create the file if it does not exist yet. I've moved this to an earlier place in the function so we don't search in files that do not exist. Aditionaly, I've created some tests for the functions in 2_Functions.R to make sure the behaviour is as expected, and stays as expected when we change it. More information on this can be found here #13 .

**Comment by naurasd** [comment]
Alright got it, thanks for the quick reply.

Would you mind sending me an e-mail ([nauras.daraghmeh@gu.se](url))?

I would like to discuss a few things.

Dank je wel!

**Comment by TimBosman** [comment]
Great, I will send an email and this issue will be closed when we merge the Pull request.

**Comment by naurasd** [comment]
Perfect!
